# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Pressthe8 Blog"
description: > # this means to ignore newlines until "email:"
   Project updates from Pressthe8

email: info@pressthe8.com
#blog logo
logo: "/assets/images/pressthe8_logo_300x300.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/pressthe8_background.png"

name: 'Jamie Reeve'
author: 'Jamie Reeve'
author_image: "/assets/images/JR.png"

paginate:	5

url: "https://blog.pressthe8.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_pressthe8'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_pressthe8
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/reeviobot
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
